# Theme settings
doks:
    baseurl:
    color_theme: green # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text:
            image: true
        nav:
            - item_name: Allgemeines
              item_url: '/allgemeines'
            - item_name: Inhalt
              item_url: '/inhalt'
            - item_name: Funktionen
              item_url: '/funktionen'
            - item_name: Kontakt
              item_url: '/kontakt'
    footer:
        content:
            logo:
                text: CVS - Softwaredokumentation
                image:
            copyright: Copyright &copy; 2020. - CVS Raphael Sütterlin <br>All rights reserved.

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
future: true
